/// <reference path="../../typings/index.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../objects/asset.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../objects/gameobject.ts" />
/// <reference path="../objects/background.ts" />
/// <reference path="../objects/chimney.ts" />
/// <reference path="../objects/cookiesmilk.ts" />
/// <reference path="../objects/icicles.ts" />
/// <reference path="../objects/oogie.ts" />
/// <reference path="../objects/presents.ts" />
/// <reference path="../objects/santa.ts" />
/// <reference path="../reactions/collision.ts" />
/// <reference path="../scenes/menu.ts" />
/// <reference path="../scenes/instructions.ts" />
/// <reference path="../scenes/game.ts" />
/// <reference path="../scenes/gameover.ts" /> 
//# sourceMappingURL=_reference.js.map